name: Security audit

on:
  schedule:
    # Runs at 00:00 UTC everyday
    - cron: "0 0 * * *"
  push:
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
  pull_request:

permissions:
  contents: read
  issues: write

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache advisory database
        uses: actions/cache@v4
        with:
          path: ~/.cargo/advisory-db
          key: advisory-db-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: advisory-db-

      - name: Install cargo-audit
        uses: taiki-e/install-action@2ca9b94c269419b7b0c711c09d0b21c4e1d51145  # v2.83.1
        with:
          tool: cargo-audit

      - name: Run security audit
        run: cargo audit
